from backend.app.storage.schema import Column, ColumnGroup as G, Database, ForeignKey, Index, Table, UniqueConstraint, CheckConstraint, non_blank_sql

def c(name, group=G.DATA, typ='TEXT', nullable=False, **rules): return Column(name,typ,group,nullable=nullable, **rules)
BODY_METRIC_DATABASE_SCHEMA = Database(name='body_metrics.db', tables=(
    Table(name='body_records', columns=(c('record_id',G.PRIMARY_KEY),c('member_id',G.SCOPE),c('kind'),c('metric',non_blank=False),c('starts_at'),c('ends_at',nullable=True,non_blank=True),c('source'),c('identity_key'),c('payload',json_kind='object'),c('source_payload',json_kind='container'),c('import_managed',G.STATE,'INTEGER'),c('edited',G.STATE,'INTEGER'),c('created_at',G.AUDIT),c('updated_at',G.AUDIT)),primary_key=('record_id',),unique_constraints=(UniqueConstraint(('member_id','identity_key')),),checks=(CheckConstraint("kind IN ('measurement','meal','sleep','workout')"),CheckConstraint('import_managed IN (0,1)'),CheckConstraint('edited IN (0,1)'),CheckConstraint("kind <> 'measurement' OR (" + non_blank_sql("metric") + ")"),CheckConstraint("(kind NOT IN ('sleep','workout') AND COALESCE(json_extract(payload,'$.precision'),'instant') = 'instant') OR ends_at IS NOT NULL")),indexes=(Index('body_member_time',('member_id','starts_at','record_id')),Index('body_member_kind_metric_time',('member_id','kind','metric','starts_at')),Index('body_member_source_time',('member_id','source','starts_at')),)),
    Table(name='body_exclusions',columns=(c('member_id',G.PRIMARY_KEY),c('identity_key',G.PRIMARY_KEY)),primary_key=('member_id','identity_key')),
    Table(name='body_imports',columns=(c('import_id',G.PRIMARY_KEY),c('member_id',G.SCOPE),c('actor_account_id',G.SCOPE),c('request_id'),c('filename'),c('sha256'),c('payload',json_kind='object'),c('state',G.STATE),c('created_at',G.AUDIT),c('updated_at',G.AUDIT)),primary_key=('import_id',),unique_constraints=(UniqueConstraint(('member_id','actor_account_id','request_id')),),checks=(CheckConstraint("state IN ('preview','running','complete','failed')"),)),
    Table(name='body_import_records',columns=(c('import_id',G.PRIMARY_KEY),c('record_id',G.PRIMARY_KEY)),primary_key=('import_id','record_id'),foreign_keys=(ForeignKey(('import_id',),'body_imports',('import_id',),on_delete='CASCADE'),ForeignKey(('record_id',),'body_records',('record_id',),on_delete='CASCADE'))),
    Table(name='body_files',columns=(c('file_id',G.PRIMARY_KEY),c('member_id',G.SCOPE),c('record_id',G.REFERENCE),c('filename'),c('mime_type'),c('sha256'),c('image_bytes',typ='BLOB'),c('created_at',G.AUDIT)),primary_key=('file_id',),foreign_keys=(ForeignKey(('record_id',),'body_records',('record_id',),on_delete='CASCADE'),),unique_constraints=(UniqueConstraint(('record_id','sha256')),)),
))
